name: Main

on: 
  push:
    branches: [ main ]

jobs:
  main:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - run: python -m pip install click

      - run: python -m pip install pywin32 == 306
        if: ${{ matrix.os }} == 'windows-latest'

      - name: Run Python
        run: python main.py