name: Main

on: 
  push:
    branches: [ main ]

jobs:
  main:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Run Python
        run: python main.py 